hull3/gear/Katiba.h, hull3/gear/MX.h, hull3/gear/Mk20.h, hull3/gear/Tavor.h
Added Bipods + Zafir mag fixes
=> 1.42 fixes

hull3.Altis/description.ext
Supressing connect/disconnect messages + removing unused channels
```
2 = Command
4 = Vehicle
6 = System
```
=> Adding disableChannels to description.ext

hull3/mission_params.h
Value of 1 seem insanely hard to shoot in, bullets were curving in front of us! Trying these, will revise again if still too aggressive.
=> Revised wind values

hull3/assign/gear/Katiba_CN.h, hull3/assign/gear/Katiba_CSAT.h
Fixing more random gear bits, someone used a very old template for CSAT before they had their ammo adjusted by BI.
=> Correcting x51 to x54 on 7.62 ammo

hull3/mission_functions.sqf
=> Added check for ARK ACE self interact

hull3/mission_functions.sqf
Reference: https://github.com/kami-/hull3/issues/57
Tested the command in dedi, works for JIP accurately
=> Updating fog to use new bis_fnc

hull3/hull3.h, hull3/settings_functions.sqf
=> Adding disableRemoteSenors to NonStandardGeneralSettings

hull3/assign/gear/AR15_ASA.h, hull3/assign/gear/AUGA3_AUS.h, hull3/assign/gear/AUGA3_IRE.h, hull3/assign/gear/AUGA3_NZ.h, hull3/assign/gear/FAL_ARC.h, hull3/assign/gear/FAL_PMC.h, hull3/assign/gear/G3KA4_NOR.h, hull3/assign/gear/M16A2_US.h, hull3/assign/gear/M16A4_CAN.h, hull3/assign/gear/M16A4_ROK.h, hull3/assign/gear/M4A1_US.h, hull3/assign/gear/M4_US.h, hull3/assign/gear/SCAR_L_US.h
=> Swapping Toadies M249s to CUPs

hull3/assign/gear/AEK_RU.h, hull3/assign/gear/AK74_DPR.h, hull3/assign/gear/AK74_UKR.h, hull3/assign/gear/AKM_IRN.h, hull3/assign/gear/G3A3_IRN.h, hull3/assign/gear/Katiba_IRN.h, hull3/assign/gear/SCAR_H_US.h, hull3/assign/uniform/AUS_AMCU.h, hull3/assign/uniform/CN_WD2.h, hull3/assign/uniform/DPR_AUT.h, hull3/assign/uniform/DPR_SUM.h, hull3/assign/uniform/IRN_DE.h, hull3/assign/uniform/IRN_QF_DE.h, hull3/assign/uniform/IRN_QF_WD.h, hull3/assign/uniform/IRN_RG_DE.h, hull3/assign/uniform/IRN_RG_WD.h, hull3/assign/uniform/IRN_WD.h, hull3/assign/uniform/RU_REED.h, hull3/assign/uniform/UKR_TTSKO.h, hull3/assign/uniform/USA_MC.h, hull3/assign/uniform/USA_MC_DRK.h, hull3/assign/uniform/USA_RAN_SCO.h, hull3/assign/uniform/USA_SCO.h, hull3/factions.h
Adds New US, UKR, AUS, IRN, RU, CN, DPR Factions
=> Update to support new unit patch

hull3/assign/gear/Katiba_CN.h, hull3/assign/gear/Katiba_CSAT.h, hull3/assign/gear/Katiba_IRN.h, hull3/assign/uniform/CUP_RACS_URB.h
Ignore the thing about uniform classes, that was already merged so *shouldn't* change anything.
=> Fixes missing tracer mags for Katiba loadout

hull3/assign/gear/AR15_ASA.h, hull3/assign/gear/HK416.h, hull3/assign/gear/HK416_KSK.h, hull3/assign/gear/M16A2_US.h, hull3/assign/gear/M16A3_RACS.h, hull3/assign/gear/M16A4_CAN.h, hull3/assign/gear/M16A4_ROK.h, hull3/assign/gear/M16A4_USMC.h, hull3/assign/gear/M4A1_US.h, hull3/assign/gear/M4A1_USMC.h, hull3/assign/gear/M4_US.h, hull3/assign/gear/MIX_LVM.h
Switching out to use BI 5.56 over RHs.
Switching out RH M4A1s + M4s to use Toadies.
=> M4 and 5.56 ammo adjustments

hull3/assign/gear/HK416.h, hull3/assign/gear/HK416_KSK.h
Front post clips with the low mount.
=> Fixing low scopes on M4s

hull3/assign/gear/G36_GER.h, hull3/assign/gear/G36_KSK.h, hull3/factions.h, hull3/hull3.h
Two sets of G36, one with regular dual-optic, one with Rail mounted dot sights
=> Adding G36's

hull3/assign/gear/CAR15_GEND.h, hull3/assign/gear/CAR15_US.h, hull3/assign/uniform/GEND_COP.h, hull3/assign/uniform/GEND_SWAT.h
Fixes #107 with new classnames/gear
=> Fix for GEND Gear

hull3.Altis/description.ext
Old syntax should work for a while but probably better to update this now
=> Updating disableChannels to newer syntax

hull3/acre_functions.sqf, hull3/hull3.h
Adjusting ACRE settings to work with the new 901 release
=> Adjustments for updated ACRE

hull3/assign/gear/AUGA3_AUS.h, hull3/assign/gear/AUGA3_IRE.h, hull3/assign/gear/AUGA3_NZ.h, hull3/assign/gear/G36_GER.h, hull3/assign/gear/G36_KSK.h, hull3/assign/gear/L85_BAF.h, hull3/assign/gear/L85_BAF_RIS.h, hull3/assign/gear/M16A4_CAN.h
Fix due to CUP bug with weapon.
=> Replacing L7 with M240

hull3/hull3.h
Tweaking a few settings based off play testing.
=> Adjusting ACRE terrain loss

hull3/acre_functions.sqf, hull3/hull3.h
Not tested, needs new version of ACRE before merge.
=> ACRE2 new API call added

hull3/assign/uniform/IF44_GER_W_U.h, hull3/assign/uniform/IF44_USSR_W_U.h
=> Winter uniform tweaks

hull3/acre_functions.sqf, hull3/hull3.h
Using CBA settings going forward
=> Removal of ACRE API commands

hull3/assign/gear/AKS74_CDF.h, hull3/assign/gear/M16A3_CDF.h, hull3/assign/uniform/CUP_BAF_MTP.h, hull3/assign/uniform/CUP_CDF_DES.h, hull3/assign/uniform/CUP_CDF_DES_UN.h, hull3/assign/uniform/CUP_CDF_FOR.h, hull3/assign/uniform/CUP_CDF_FOR_UN.h, hull3/assign/uniform/CUP_CDF_MOU.h, hull3/assign/uniform/CUP_CDF_MOU_UN.h, hull3/assign/uniform/CUP_RACS_MECH.h, hull3/factions.h
6 CDF Factions (UN/Non-UN)
RACS Mechanised Faction
AKS74 CDF gear
M16A3 UN gear
=> Gear and uniform updates

hull3/assign/gear/AUGA3_IRE.h, hull3/assign/gear/CAR95_CN.h
Fixes for issues #158 and #155.
=> Minor gear fixes

hull3/briefing/hull3.sqf
As per https://community.bistudio.com/wiki/Structured_Text#Hyperlink this makes the links in the briefing clickable (in case somebody is interesting enough to do this... during briefing... )
=> Make the links clickable

hull3/assign/uniform/Default.h
Looks like a regex replacement casualty...
=> Fixing broken default template

hull3/assign/gear/M14_COLT.h, hull3/assign/uniform/USA_OD.h, hull3/factions.h, hull3/hull3.h
Checked with parser and RPT clean.
=> Adding vietnam era loadout

hull3/assign/gear/M14_COLT.h
=> Fixing array error

hull3/hull3.h, hull3/settings_functions.sqf
ACE3 does this with an EH, one less thing for us to look after https://github.com/acemod/ACE3/pull/5354
=> Removing hull3 rating fix

hull3/assign/gear/ACR_BLK_PMC.h, hull3/assign/gear/ACR_TAN_PMC.h, hull3/assign/gear/AUGA3_AUS.h, hull3/assign/gear/AUGA3_IRE.h, hull3/assign/gear/AUGA3_NZ.h, hull3/assign/gear/CAR15_GEND.h, hull3/assign/gear/G36_GER.h, hull3/assign/gear/G36_KSK.h, hull3/assign/gear/G3KA4_NOR.h, hull3/assign/gear/HK416_CTRG_BLK.h, hull3/assign/gear/HK416_CTRG_DE.h, hull3/assign/gear/HK416_CTRG_TRP.h, hull3/assign/gear/HK416_KSK.h, hull3/assign/gear/L85_BAF.h, hull3/assign/gear/L85_BAF_RIS.h, hull3/assign/gear/M14_US.h, hull3/assign/gear/M16A2_US.h, hull3/assign/gear/M16A3_CDF.h, hull3/assign/gear/M16A3_RACS.h, hull3/assign/gear/M16A4_CAN.h, hull3/assign/gear/M16A4_ROK.h, hull3/assign/gear/M4A1_US.h, hull3/assign/gear/M4_US.h, hull3/assign/gear/MP5_GEND.h, hull3/assign/gear/SCAR_H_US.h, hull3/assign/gear/SCAR_L_PMC.h, hull3/assign/gear/SCAR_L_US.h
Nicer model, smaller ammo, better scope.
=> Switch CUP MAAWS to vanilla

hull3/config.cpp, hull3/eden_functions.sqf, hull3/mission_functions.sqf
=> Eden EHs to force correct weather

hull3/eden_functions.sqf, hull3/mission_functions.sqf
=> Standardising default dates across hull

hull3/mission_functions.sqf
`setfog` isn't syncing properly in MP, client gets 0, server has 0.4.
Hoping this works better...
=> Reverting to BI function for fog

hull3/mission_functions.sqf
Original implementation worked fine with 2 players, didn't with 20+.
Added large delay... maybe feex?
=> Fog still unreliable in MP

hull3/assign/uniform/CUP_BAF_DE.h, hull3/assign/uniform/CUP_BAF_MTP.h, hull3/assign/uniform/CUP_BAF_WD.h
Fixing a lot of changed classnames...
=> BAF classname overhaul

hull3/assign/gear/M4A1_USMC.h
=> Fixing our 2 CUPs 1 m4 problem

hull3/assign/gear/AKM_SYND.h
Don't merge, checking for further issues.
=> Removing duplicated line

hull3/assign/gear/CAR15_GEND.h, hull3/assign/gear/M4_US.h
Deja vu?
https://i.imgur.com/1QP7GLl.gif
=> Fixing duplicated CUP tracer mags

hull3/hull3_postinit.sqf, hull3/unit_functions.sqf
Issuing `doStop` on preInit in dedicated causes weird issues...
Used an _seemingly_ unused function, checked Hull3 and Admiral and can't see it being called so repurposed it for my need.
=> Moving disable AI movement to postInit

hull3/unit_functions.sqf
=> Fixing doStop running on non-player units

hull3/gc_functions.sqf
Must have reverted this somehow...
=> Fix function call using ark prefix

hull3/assign/uniform/PMC_CBRN.h
A bit of a place holder but all the gear works.
=> Fixing PMC CBRN gear

hull3/marker_functions.sqf
As discussed on Slack. Checked in local SP and MP.
=> Add support for assignedTeam to update FT markers

hull3/settings_functions.sqf
Noticed this command is only meant to be called post mission starting (as per bi wiki). Not had it not work but best to fix it properly.
=> Wait for mission to start before running

hull3/assign/uniform/CUP_RU_RATNIK_WD.h
Missing G from balaclava classname
=> Fixing classname

hull3/unit_functions.sqf
Init never fires in SP editor, using an or check to catch that and still run the required funcs.
Don't merge til post Saturday.
=> Handle filthy SP users

hull3.Altis/description.ext, hull3/uniform_functions.sqf, hull3/unit_functions.sqf
Removing legacy fnc replaced with description.ext setting
=> Remove fnc_assignGogglesOnJip 

hull3/assign/gear/RK62_FIN.h
Binning Toadies AKs and found a standalone version of the RK62
=> Replace HLC rk with TOB standalone

hull3/hull3.h, hull3/settings_functions.sqf
This drops some world sounds to more sensible levels, make rain less deafening etc
Influenced sounds among others are:
- forest sounds (birds, crickets, ...)  
- waves
- wind
- rain
- sounds produced by air conditioners and similar
- thunder
=> add fadeEnvironment

hull3/settings_functions.sqf
Undoes PR - https://github.com/kami-/hull3/pull/384
Due to BI fixing underly issue - https://feedback.bistudio.com/T163245 
Needs v2.08 first, merge after getting OK from me!
=> Re-add fadeRadio

hull3.Altis/description.ext, hull3/gc_functions.sqf, hull3/mission_functions.sqf, hull3/mission_params.h
A3 v2.08 added new alternate syntax for `setRain` to allow you to use a different particle and disable the annoying raining sound.
=> Add snow to default weather options
