- hull3/assign/gear/Katiba_CSAT.h
- hull3/assign/gear/MX_NATO.h
- hull3/assign/gear/Mk20_AAF_DE.h
- hull3/assign/gear/Mk20_AAF_WD.h
- hull3/assign/gear/TRG_FIA.h
NATO / AAF / CSAT have really low carry capacity in uniforms.
We've adjusted MNP to have decent space so should only effect these 4 that need a tweak.
> Fixing BI loadouts

- hull3/acre_functions.sqf
Attempting to fix people being left on alternate speaking volumes from the previous mission.
> Forcing reset of ACRE2 volume on init

- hull3.Altis/hull3/briefing/civilian.sqf
- hull3.Altis/hull3/briefing/indfor.sqf
- hull3.Altis/hull3/briefing/opfor.sqf
With this fixed, compass will be able to print briefings correctly
> Fixed incorrect breifing faction identifiers

- hull3/mission_functions.sqf
As per title, removes weapon safety from launchers but keeps it from Rifles + Pistols. Rockets still removed if fired so shouldn't have any chance of spawn death.
> Rehaul weapon safety to ignore launchers

- hull3/factions.h
As per https://github.com/kami-/hull3/issues/129
> Removing CUP_BAF_MTP from woodland

- hull3/hull3.h
- hull3/settings_functions.sqf
ST HUD now uses CBA settings so one less thing us for to maintain!
Server already configured to match existing hull settings.
> Removing ST HUD settings

- hull3/hull3.h
- hull3/settings_functions.sqf
Disables ambient animals by default.
Wabbit hunting season is over.
> Adding setting for disabling ambient animals

- hull3/assign/uniform/AUS_AMCU.h
Pilot had NATO uniform (with USA patches), removed to default back to crewman AMCU uniform.
> Fixed Pilot uniform for AUS AMCU

- hull3/assign/gear/HK416_CTRG_BLK.h
- hull3/assign/gear/HK416_CTRG_DE.h
- hull3/assign/gear/HK416_CTRG_TRP.h
- hull3/assign/gear/HK416_KSK.h
- hull3/assign/gear/M4A1_USMC.h
As per continued requests from AR users, CQC sights for M27s.
> Adding standardised bipods and scopes to M27s

- hull3/mission_functions.sqf
Did a quick local dedi test, using our existing method setting fog to Heavy in description.ext: 
bis_fnc_setFog:
`fogParams` returns: [0,0,0]
`fogForecast` returns: 0
0 setfog:
`fogParams` returns: [0.4,0,0]
`fogForecast` returns: 0.4
It looks like BI's fnc doesn't set the forecast value correctly so fog vanishes after 20 minutes or so (probably can be seen using `nextWeatherChange`).
> Reverting to old setFog method, looks more reliable in MP

- hull3/mission_functions.sqf
As per comment on: https://community.bistudio.com/wiki/setFog
Adding delay between `setOvercast` and `setFog`.
> Added delay to setFog

- hull3/mission_functions.sqf
- hull3/mission_params.h
This will remove the annoying "line of death" where the client ends up with very strange huge minus numbers for fogbase values. Also removes `date` from JIP packet, no clue what it's point was but I switched from `setDate` to the newer `BIS_fnc_setDate` which has network propagation built in.
Ideally `setFog` should work fine without the need for `remoteExec` however the client seems to pickup a weird value from `[] call hull3_mission_fnc_getFog` which causes it to derp out.
Also moved everything to params and new select syntax.
> The great fog fix

- hull3/factions.h
- hull3/mission_functions.sqf
Also changed a select syntax _apparently_. Don't remember doing this.
> Fixing legacy CUP classname

- hull3/config.cpp
- hull3/eden_functions.sqf
- hull3/mission_functions.sqf
- hull3/mission_params.h
Adjusted the Eden functions to hopefully remove the case where terrains with ground close to sea level get caught in under terrain waves.
Removed references to Humidity (killed during the Alpha of A3), shrunk the `hull3_mission_weather` array to seven elements as we never call the 8th element.
Reformatted, reviewed and adjusted the default weather conditions, there were some odd numbers used throughout so I've standardised them to what I think is a sensible level. Hopefully they're a bit more readable now too.
> Weather clean up

- hull3/assign/gear/L85_BAF.h
- hull3/assign/gear/L85_BAF_RIS.h
- hull3/assign/gear/M16A2_US.h
- hull3/assign/gear/SCAR_L_PMC.h
- hull3/assign/gear/SCAR_L_US.h
Will stop invisible and clipping mags in these templates.
There are few templates using mixed HLC/CUP loadouts that probably need a case by case review, I've left those untouched for now.
> Moving CUP 5.56 weapon to their own mag classes

- hull3/gear_functions.sqf
This is making riflemen have medic icons in the DUI squad hud. I think this is a legacy variable as I built a version without this line and we're still able to give epi/morphine etc.
> Removing legacy ACE variable

- hull3/config.cpp
- hull3/marker_functions.sqf
Retiring the old triangle for a more modern unit icon from A3.
> Fireteam marker improvements

- hull3/hull3.h
- hull3/marker_functions.sqf
Added support for setting alpha values on markers created by Hull. Written to keep supporting old calls and fall back to a value of 1 is the arg isn't passed so doesn't break any existing configurations.
In the future I'll add the ability to set alpha to `hull3_marker_fnc_addCustomMarker` too.
By default I've dropped the FireTeamMemberMarker to 50% alpha so that it doesn't over power the Squad markers. I'll update this a bit more based on feedback in sessions.
> Adds support for Hull markers to have an alpha value

- hull3/marker_functions.sqf
Already passes an array, this means it ends up nesting it and breaking.
> Fixing custom markers

- hull3/unit_functions.sqf
Quick test in local MP seems to work, is under a `local` check so shouldn't run on players.
You can still order AI to move it just stops them initially moving on their own and causing issues, e.g. if you leave AI in a player controlled team and the FTL moves, the AI won't follow anymore unless ordered.
> Stop AI units moving around when in building/over water

- hull3/gc_functions.sqf
- hull3/hull3.h
- hull3/hull3_postinit.sqf
I've simplified a lot of this to hopefully make it leaner and faster. I've tried to keep to the same principals as the existing GC to not cause any major issues and shouldn't effect any older missions (I hope...)
- No more element specific time checks (they never worked in the existing code)
- No more group clean up settings (Not sure why you'd ever need to keep empty groups + engine now cleans them up, see Admiral PR)
- Removed spawn and while loops, using one CBA PFH and an EH to track the dead
- Deletes oldest units first so should take car of 90% of the issues where bodies vanish as you're shooting them
> Garbage cleaner rewrite

- hull3/gc_functions.sqf
Following on from the rewrite after some _heavy_ testing last night I noticed that the `entityKilled` EH returns all entities (that should have been obvious). So while I was filtering `CAManBase` in to one array, the wrecks array was full of `Static` classes (buildings/fences destroyed).
Did some code testing to figure out the fastest method to do this (don't want overhead here as it runs any time anything dies). The exitWith is the fastest method 0.0034ms overhead to filter out the crap. Seems acceptable!
> GC improvement

- hull3/assign/gear/CAR15_GEND.h
- hull3/assign/gear/M14_US.h
- hull3/assign/gear/M16A1_US.h
- hull3/assign/gear/M16A2_US.h
- hull3/assign/gear/M16A4_ROK.h
- hull3/assign/gear/MP5_GEND.h
1:1 with current assignment of original m60 vs E4 variant, plus red tracer for everyone.
> Change m60s to CUP

- hull3/acre_functions.sqf
- hull3/gear_functions.sqf
Moved everything out of scheduled space to avoid potential hangs in postInit.
Tested on dedi, with JIP, no issues so far. Will need real-world testing to see if there are any other issues. For @kami- 's sanity the flow looks like this.
CBA WUAE directly in postInit that waits for ACRE to replace any `itemRadio` items. Once this is done the gear script removes any radios (slight improvement here as the code doesn't run is there are no radios on you). Then we CBA WUAE for `hull3_gear_radiosAssigned` to be true and `acre_api_fnc_isInitialized` to be true again (as it runs each time you adds radios) then we set the channels.
This is as clean as I can get it, seems to work well! 🤞
> ACRE init overhaul

- hull3/mission_functions.sqf
- hull3/unit_functions.sqf
Nice new public function checks for empty weapons so can dump our check, it also checks to see if the weapon is already set to safe and skips it so another check we can remove.
Switched to `ace_firedPlayer` EH since it picks up both standard fired EH bits plus the ACE advanced throwing (including cooking nades). Doing the check on `weapons player` covers primary, secondary and launchers so less likely to have a fuck up there.
Added bonus that we auto set weapons to fire after safety is off so no need to cycle 3 weapons manually toggling it off. Checked in SP and self-hosted and it's all fine. Functions fully local so shouldn't need a dedi test.
> Adding new public ACE safety fnc

- hull3/mission_functions.sqf
- hull3/mission_params.h
Removed the use of `setWindStr` which operates in a 0..1 range for `setWind` which is m/s.
I've picked values based on their sound cues, 1m/s for "no wind" so things still move around a bit, looks weird with all the trees and grass being totally static. Only slightly effects smoke and ballistics don't care about wind. 5m/s for light, this has a slight sound with it. 10m/s for strong wind, again more intense sound. 20m/s for storm, it's pretty intense...
Wind will always blow NE as if you leave direction not forced it flicks directions erratically and does weird things. If wanted I could add another line to `setWindDir random 360` to vary this, not sure if anyone is that fussed!
Finally I've left in `setWindForce` but zero'd all the values as to not break existing missions. In an ideal …
> Fixing wind to use global command

- hull3.Altis/description.ext
- hull3/config.cpp
ARK Inhouse takes care of moving people to spec, the Hull3 event should still fire with the suggested config changes.
> Adjust Hull to use respawn type "NONE"

- hull3/gc_functions.sqf
Not sure when this started happening but I noticed that vehicles were being deleted nearly instantly when they exploded. Looking at the array, it was filled with `<NULL-object>`.
Not sure if this is off the back of an ACE update or something but `entityKilled` is returning a lot of garbage now. Example:
```
0:08:01 "O Charlie 3-4:3 REMOTE"
0:08:01 "<NULL-object>"
0:08:28 "O Charlie 2-4:1 REMOTE"
0:08:28 "<NULL-object>"
0:08:31 "O Charlie 1-1:2 REMOTE"
0:08:31 "<NULL-object>"
```
or
```
0:09:00 "2a6af13d600# 587069: zastavka_jih.p3d"
0:09:00 "<NULL-object>"
0:09:00 "<NULL-object>"
0:09:00 "<NULL-object>"
0:09:00 "<NULL-object>"
0:09:00 "<NULL-object>"
0:09:00 "<NULL-object>"
0:09:00 "<NULL-object>"
0:09:00 "<NULL-object>"
0:09:00 "<NULL-object>"
0:09:01 "<NULL-object>"
0:09:01 …
```
> Fixing nullObj being passed in entityKilled

- hull3/assign/uniform/RU_CBRN.h
Seeing as this is the only faction that's used in a mission anywhere, I've hotfixed it to use gear that exists. They could probably do with a proper adjustment as per all the other CBRN templates but this at least will load without errors if used.
> Temp fixing RU_CBRN

- hull3/hull3.h
- hull3/hull3_preinit.sqf
- hull3/settings_functions.sqf
Kills off `BIS_noCoreConversations` which is legacy and stopped working a while ago.
It also removes all preInit calls for settings, since all of them are now postInit only. Not sure if this is removing too much? @kami-
> Removing ghost in the shell

- hull3/acre_functions.sqf
- hull3/logbook.h
- hull3/mission_functions.sqf
Since merging of PR https://github.com/kami-/hull3/pull/377 apparently `enableRadio` also stops the use speaking through the AI via script, e.g. `player sideChat "test"`. However `systemChat` doesn't care about the unit so still functions.
I personally think this looks a bit cleaner anway.
Mission safety off:
Logbook on trace:
Will require PRs for Admiral for logbook too!
> Move logging/alerts to systemChat

- hull3/gear_functions.sqf
- hull3/hull3.h
Automatically adds the ARK medical crate to any vehicle with a hull init call. Can be disabled in hull3.h if mission maker wants to limit medical supplies.
> Add vehicle medical crates

- hull3/marker_functions.sqf
Binning off the CBA implementation for native engine one.
Dropping the "MAIN" var as `getOrDefault` just returns `"ColorWhite` if it doesn't match a known colour.
> use native hashMap

- hull3/gear_functions.sqf
- hull3/hull3.h
- hull3/mission_functions.sqf
Switched from a hardcoded time function to using `getLighting` which reports a number based on weather/terrain. Means weird terrains like Caribou shouldn't have night gear during the day etc. I removed `hull3_mission_fnc_isNightTime` function as it's only called here and we can just use one command to replace it. Expanded the logging a bit so I can debug it if it does anything weird. The magic number is roughly what I get around 60-45 minutes before it's "dark" on a few terrains, so if you start as the lights fading you'll keep your night equipment.
Expanded the clean up to all ACE chemlights + maplights.
Only thing I don't like is waiting 10 seconds but I couldn't find an event or anything to hook to make sure the client's date/time has been sync'd from the server so I figured 10 seconds …
> Improve hull3_gear_fnc_tryRemoveNightGear

- hull3/acre_functions.sqf
Currently there isn't any catch-all for if people define a custom unit template and then don't re-add the default languages. This just means everyone has babel and can't understand each other. 
This PR now means they just get auto-assigned every available language.
> Handle broken languages better

- hull3/gc_functions.sqf
If you use `dynamicSimulation` on AI (as we do for CQC/sentries) if they take a fatal amount of damage they still "die" but as simulation is disabled the model remains frozen in a standing animation.
I happened to noticed while testing that the `EntityKilled` EH was still firing on them even though they weren't be actively simulated. This lead to doing some testing and finding that we can use this event to `enableSimulation` on the AI that's died to have it move to ragdoll. This has been a bit of a bugbear since we added this system and is one of the most annoying parts, hopefully fixed!
I wasn't quite sure where this wanted to live as dynamicSim is configured from Admiral but we're already hooking the EH in Hull for GC so I figured it makes more sense to be here.
> Handle dynamicSim AI standing post death
